QLNV/Controllers/ADMsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using QLNV.Model;

namespace QLNV.Controllers
{
    public class ADMsController : Controller
    {
        private DBnhanvien db = new DBnhanvien();

        // GET: ADMs
        public ActionResult Index()
        {
            return View(db.ADMs.ToList());
        }
        //For UserName
        public JsonResult IsUserNameExits(String UserName)
        {
            return Json(!db.ADMs.Any(x => x.TenDN == UserName), JsonRequestBehavior.AllowGet);
        }
    


        // GET: ADMs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ADM aDM = db.ADMs.Find(id);
            if (aDM == null)
            {
                return HttpNotFound();
            }
            return View(aDM);
        }

        // GET: ADMs/Create
        public ActionResult Create()
        {
            return View();
        }
    
        // POST: ADMs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDadm,TenDN,Pass")] ADM aDM)
        {
            if (ModelState.IsValid)
            {
                db.ADMs.Add(aDM);
                db.SaveChanges();
                TempData["AltertMessage"] = "Tạo Thành Công!";
                return RedirectToAction("Index");
            }
                return View(aDM);
        }
        //Get: ADM/Login
        public ActionResult Login()
        {
            return View();
        }
        //POST:ADM/Login
        [HttpPost]
        public ActionResult Login(ADM usr)
        {
            var u = db.ADMs.SingleOrDefault(m => m.TenDN == usr.TenDN && m.Pass == usr.Pass);
            if (u != null)
            {

                Session["LoginSuccess"] = usr;
                return RedirectToAction("Index", "BangNV");
            }
            else
            {
                TempData["error"] = "Tài Khoản Admin Không Đúng!";
                return View();
            }    

            
        }
        // GET: ADMs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ADM aDM = db.ADMs.Find(id);
            if (aDM == null)
            {
                return HttpNotFound();
            }
            return View(aDM);
        }
        //Get: ADM/Logout
        public ActionResult Logout()
        {
            Session["LoginSuccess"] = null;
            return RedirectToAction("Index", "BangNV");
        }




        // POST: ADMs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDadm,TenDN,Pass")] ADM aDM)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aDM).State = EntityState.Modified;
                db.SaveChanges();
                TempData["AltertMessage"] = "Sửa Thành Công!";
                return RedirectToAction("Index");
            }
            return View(aDM);
        }

        // GET: ADMs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ADM aDM = db.ADMs.Find(id);
            if (aDM == null)
            {
                return HttpNotFound();
            }
            return View(aDM);
        }

        // POST: ADMs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ADM aDM = db.ADMs.Find(id);
            db.ADMs.Remove(aDM);
            db.SaveChanges();
            TempData["AltertMessage"] = "Xóa Thành Công!";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLNV/Controllers/ChucVusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLNV.Model;

namespace QLNV.Controllers
{
    public class ChucVusController : Controller
    {
        private DBnhanvien db = new DBnhanvien();

        // GET: ChucVus
        public ActionResult Index()
        {
            return View(db.ChucVus.ToList());
        }

        // GET: ChucVus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChucVu chucVu = db.ChucVus.Find(id);
            if (chucVu == null)
            {
                return HttpNotFound();
            }
            return View(chucVu);
        }

        // GET: ChucVus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ChucVus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDChucVu,TenChucVu")] ChucVu chucVu)
        {
            if (ModelState.IsValid)
            {
                db.ChucVus.Add(chucVu);
                db.SaveChanges();
                TempData["AltertMessage"] = "Tạo Thành Công!";
                return RedirectToAction("Index");
            }

            return View(chucVu);
        }

        // GET: ChucVus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChucVu chucVu = db.ChucVus.Find(id);
            if (chucVu == null)
            {
                return HttpNotFound();
            }
            return View(chucVu);
        }

        // POST: ChucVus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDChucVu,TenChucVu")] ChucVu chucVu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chucVu).State = EntityState.Modified;
                db.SaveChanges();
                TempData["AltertMessage"] = "Sửa Thành Công!";
                return RedirectToAction("Index");
            }
            return View(chucVu);
        }

        // GET: ChucVus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChucVu chucVu = db.ChucVus.Find(id);
            if (chucVu == null)
            {
                return HttpNotFound();
            }
            return View(chucVu);
        }

        // POST: ChucVus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ChucVu chucVu = db.ChucVus.Find(id);
            db.ChucVus.Remove(chucVu);
            db.SaveChanges();
            TempData["AltertMessage"] = "Xóa Thành Công!";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLNV/Controllers/KhuLamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLNV.Model;

namespace QLNV.Controllers
{
    public class KhuLamsController : Controller
    {
        private DBnhanvien db = new DBnhanvien();

        // GET: KhuLams
        public ActionResult Index()
        {
            return View(db.KhuLams.ToList());
        }

        // GET: KhuLams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhuLam khuLam = db.KhuLams.Find(id);
            if (khuLam == null)
            {
                return HttpNotFound();
            }
            return View(khuLam);
        }

        // GET: KhuLams/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KhuLams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDKhu,TenKhu")] KhuLam khuLam)
        {
            if (ModelState.IsValid)
            {
                db.KhuLams.Add(khuLam);
                db.SaveChanges();
                TempData["AltertMessage"] = "Tạo Thành Công!";
                return RedirectToAction("Index");
            }

            return View(khuLam);
        }

        // GET: KhuLams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhuLam khuLam = db.KhuLams.Find(id);
            if (khuLam == null)
            {
                return HttpNotFound();
            }
            return View(khuLam);
        }

        // POST: KhuLams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDKhu,TenKhu")] KhuLam khuLam)
        {
            if (ModelState.IsValid)
            {
                db.Entry(khuLam).State = EntityState.Modified;
                db.SaveChanges();
                TempData["AltertMessage"] = "Sửa Thành Công!";
                return RedirectToAction("Index");
            }
            return View(khuLam);
        }

        // GET: KhuLams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhuLam khuLam = db.KhuLams.Find(id);
            if (khuLam == null)
            {
                return HttpNotFound();
            }
            return View(khuLam);
        }

        // POST: KhuLams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KhuLam khuLam = db.KhuLams.Find(id);
            db.KhuLams.Remove(khuLam);
            db.SaveChanges();
            TempData["AltertMessage"] = "Xóa Thành Công!";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLNV/Controllers/LuongsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLNV.Model;

namespace QLNV.Controllers
{
    public class LuongsController : Controller
    {
        private DBnhanvien db = new DBnhanvien();

        // GET: Luongs
        public ActionResult Index()
        {
            return View(db.Luongs.ToList());
        }

        // GET: Luongs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Luong luong = db.Luongs.Find(id);
            if (luong == null)
            {
                return HttpNotFound();
            }
            return View(luong);
        }

        // GET: Luongs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Luongs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDLuong,SoLuong")] Luong luong)
        {
            if (ModelState.IsValid)
            {
                db.Luongs.Add(luong);
                db.SaveChanges();
                TempData["AltertMessage"] = "Tạo Thành Công!";
                return RedirectToAction("Index");
            }

            return View(luong);
        }

        // GET: Luongs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Luong luong = db.Luongs.Find(id);
            if (luong == null)
            {
                return HttpNotFound();
            }
            return View(luong);
        }

        // POST: Luongs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDLuong,SoLuong")] Luong luong)
        {
            if (ModelState.IsValid)
            {
                db.Entry(luong).State = EntityState.Modified;
                db.SaveChanges();
                TempData["AltertMessage"] = "Sửa Thành Công!";
                return RedirectToAction("Index");
            }
            return View(luong);
        }

        // GET: Luongs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Luong luong = db.Luongs.Find(id);
            if (luong == null)
            {
                return HttpNotFound();
            }
            return View(luong);
        }

        // POST: Luongs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Luong luong = db.Luongs.Find(id);
            db.Luongs.Remove(luong);
            db.SaveChanges();
            TempData["AltertMessage"] = "Xóa Thành Công!";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLNV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link href="~/Public/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="~/Public/dist/css/adminlte.min.css" rel="stylesheet" />
    <link href="~/Public/css/LayoutAdmin.css" rel="stylesheet" />
    <link href="~/Content/all.css" rel="stylesheet" />
    @RenderSection("header", required: false)
</head>

<style>
    .btb{
        margin-left:10px;
        text-align:end;
    }
    .btb a {
        font-size: 20px;
        color: blue;
        font-weight: bold;
    }
  
    .btt a{
        font-size: 20px;
        color: blue;
        font-weight: bold;
    }
    .nav-item{
        padding-top:10px;
        padding-left:5px;
    }
    .nav-item:hover{
        background-color:cornflowerblue;
    }
    .nav-item a{
        font-weight:bold;
    }
   .fa-user{
       width:10%;
       float:left;
       color:aliceblue;
   }
   .fa-house{
       font-size:20px;
       color:blue;
   }
    .fa-right-from-bracket {
        padding-left:5px;
        font-size: 20px;
        color: blue;
    }
</style>


<body class="hold-transition sidebar-mini">

    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>

                <button type="button" class="btt btn-success"> <i class="fa-solid fa-house"></i> @Html.ActionLink("Danh Sách Nhân Viên", "Index", "BangNV") </button>
                @if (Session["LoginSuccess"] != null)
                {
                   <button type="button" class="btb btn-success"> @Html.ActionLink("Đăng Xuất", "Login", "ADMs") <i class="fa-solid fa-right-from-bracket"></i></button>
                }
                else
                {
                   
                 <button type="button" class="btb btn-success"> @Html.ActionLink("Đăng Xuất", "Login", "ADMs" ) <i class="fa-solid fa-right-from-bracket"></i></button>
                }

            </ul>
            <!-- Right navbar links -->
     


                <!-- Messages Dropdown Menu -->
              

                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="~/Public/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        Brad Diesel
                                        <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">Call me whenever you can...</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                    </div>
               
                <!-- Notifications Dropdown Menu -->
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="" class="brand-link">
                <img src="~/Public/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Admin</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    
                    <div class="info">
                        <a href="#" class="d-block">Quản Lý Nhân Viên</a>
                    </div>
                </div>

                <!-- SidebarSearch Form -->
                <div class="form-inline">
                    <div class="input-group" data-widget="sidebar-search">
                        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-sidebar">
                                <i class="fas fa-search fa-fw"></i>
                            </button>
                        </div>
                    </div>
                </div>
              
       
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->

                        <li class="nav-item">
                            <i class="fa-solid fa-user"></i>
                            <a>
                                <p>
                                    @Html.ActionLink("Quản Lý Nhân Viên", "index", "NhanViens")
                                </p>
                            </a>
                        </li>



                        <li class="nav-item">
                            <i class="fa-solid fa-user"></i>
                            <a>

                                <p> @Html.ActionLink("Quản Lý Chức Vụ", "index", "ChucVus") </p>
                            </a>

                        </li>


                        <li class="nav-item">
                            <i class="fa-solid fa-user"></i>
                            <a>

                                <p>
                                    @Html.ActionLink("Quản Lý Khu Làm Việc", "index", "KhuLams")
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <i class="fa-solid fa-user"></i>
                            <a>
                                <p>
                                    @Html.ActionLink("Quản Lý Lương", "index", "Luongs")
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <i class="fa-solid fa-user"></i>
                            <a>
                                <p>
                                    @Html.ActionLink("Quản Lý Hợp Đồng", "index", "HopDongs")
                                </p>
                            </a>
                        </li>



                    </ul>

                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        @RenderBody()

        <footer class="main-footer">
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>





    <script src="~/Public/plugins/jquery/jquery.min.js"></script>
    <script src="~/Public/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="~/Public/dist/js/adminlte.min.js"></script>
    <script src="~/Public/dist/js/demo.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
    @RenderSection("footer", required: false)
</body>
</html>

QLNV/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @RenderSection("header", required: false)
</head>
<body>
    <div>
        @RenderBody()
    </div>
 
</body>
</html>